language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_script: ./node_modules/.bin/tslint --project .
scripts: npm install codecov -g

after_success:
  npm run coverage